Algoritmo "AreaDoQuadreado"
// Disciplina   : PA
// Professor   : Edilms Bindá
// Turma : 1°C / B
// Autor(a)    : Vinícius Araujo Ramos
// Data atual  : 09/03/2023
Var
lado, area: real


//Entrada


inicio

escreval (" digite o lado do quadrado: ")
leia(lado)


//Processamento
area <- lado * lado


//Saida
escreval ("a area do quadrado em metros quadrado é: ", area)


Fimalgoritmo