Algoritmo "DolarEmReal"
// Disciplina   : PA
// Professor   : Edilma Bindá
// Sala : 1ºC
// Autor(a)    : Vinícius Araujo Ramos
// Data atual  : 09/03/2023
Var
dolar,cotacao, reaal: real

Inicio
// entrada

  escreval (" escreva a quantia que possui em dolar: ")
  leia (dolar)
  escreval (" escreva a cotação do dolar: ")
  leia (cotacao)

//processamento

 reaal <- dolar* cotacao

//final

 escreval (" você possui em reais:" ,reaal)

Fimalgoritmo